#This is a generated script
#PBS -l walltime=2:00:00 
#PBS -q testflight-coda
#PBS -j oe 
#PBS -o psi4.output.$PBS_JOBID
cd $PBS_O_WORKDIR 
module load pace/2020.01
module load psi4/1.3.2
modulecount=`module -t list 2>&1|wc -l`
MACHINEFILE=$PBS_NODEFILE
NPROCS=`wc -l < ${PBS_NODEFILE}`
for i in {1..5};do
tempdir=run$i-psi4-$NPROCS+`date +%Y-%m-%d_%H_%M`
mkdir $tempdir 
cd $tempdir 
cp -r $PBS_O_WORKDIR/../../Application/Input/psi4/* .
EXE=`which psi4`>> log.out
echo $EXE>>log.out
ldd $EXE >>log.out
echo md5 >>log.out
echo `which psi4|xargs md5sum|cut -d " " -f1` >>log.out
(time   psi4 input.dat -n$NPROCS) 2>&1| tee -a time.output
echo "Running success(0)/failed(1) "${PIPESTATUS[0]} >>log.out
cd ../ ;done
